### ISSUE TITLE
comma separated `[in]` query with spaces fails

### ISSUE THREAD

**Issue by cachrisman** [dlitvakb/inline-reference-checkbox#4]
https://github.com/contentful/inline-reference-checkbox/blob/ddabf3f8e80b7d40f9a3a1bf4e5bb23138593e08/src/index.js#L36

this line should be as follows:

```const query = referenceContentTypes.length > 0 ? {"sys.contentType.sys.id[in]": referenceContentTypes.join(",")} : {}```

notice the lack of a space when joining the array of reference content types.

**Comment by dlitvakb** [comment]
Fixed
